name: Sonar Qube Scan

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
jobs:
  sonar-job:
    #    needs: security_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch || github.event.inputs.branch || github.ref_name }}
          fetch-depth: 0
          submodules: recursive

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ github.event.repository.name }}.${{ github.ref_name }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*.java,**/node_modules/**,**/*.json
            -Dsonar.language=js,ts
            -Dsonar.sourceEncoding=UTF-8
